version: '3.8'
services:
    azure-sat-api:
        container_name: azure-sat-api
        build: ./common
        volumes:
            - ./azure-sat-api:/usr/src/app
        networks:
            - azureGarden
        ports:
            - 3010:3010
        working_dir: /usr/src/app
        command: bash -c "npm install && npm run server"
    dashboard:
        container_name: dashboard
        build: ./common
        volumes:
            - ./dashboard:/usr/src/app
        networks:
            - azureGarden
        depends_on:
            - azure-sat-api
        ports:
            - 3011:3011
        working_dir: /usr/src/app
        command: bash -c "npm install && npm run server && npm run set:tailwind"
networks:
  azureGarden:
    driver: bridge
