#define IOT_CONFIG_WIFI_SSID 
#define IOT_CONFIG_WIFI_PASSWORD
#define IOT_CONFIG_IOTHUB_FQDN
#define IOT_CONFIG_DEVICE_ID
#define IOT_CONFIG_DEVICE_KEY 
#define AZ_IOT_DEFAULT_MQTT_CONNECT_PORT 8883
#define IOT_CONFIG_SAS_TOKEN "SharedAccessSignature sr="